In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Salary_Data.csv')

In [4]:
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [5]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [8]:
df.shape

(30, 2)

In [9]:
# divide data into independent and dependent variable
x= df.drop('Salary',axis=1)

In [10]:
x

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [11]:
y = df[['Salary']]

In [12]:
y

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [15]:
x_train

    YearsExperience
29             10.5
10              3.9
0               1.1
11              4.0
5               2.9
26              9.5
4               2.2
27              9.6
23              8.2
22              7.9
25              9.0
6               3.0
17              5.3
12              4.0
28             10.3
13              4.1
7               3.2
8               3.2
19              6.0
18              5.9
16              5.1
24              8.7
9               3.7
3               2.0

In [16]:
x_test

    YearsExperience
15              4.9
1               1.3
20              6.8
14              4.5
21              7.1
2               1.5

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
lr = LinearRegression()

In [19]:
lr.fit(x_train,y_train) #model fit

LinearRegression()

In [21]:
prediction = lr.predict(x_test)

In [22]:
y_test['prediction_salary']=prediction

In [23]:
y_test

     Salary  prediction_salary
15  67938.0       72014.427434
1   46205.0       37906.665034
20  91738.0       90015.746479
14  61111.0       68224.676056
21  98273.0       92858.060012
2   37731.0       39801.540723

In [26]:
df2 = pd.concat([x_test,y_test],axis=1)

In [27]:
df2

    YearsExperience   Salary  prediction_salary
15              4.9  67938.0       72014.427434
1               1.3  46205.0       37906.665034
20              6.8  91738.0       90015.746479
14              4.5  61111.0       68224.676056
21              7.1  98273.0       92858.060012
2               1.5  37731.0       39801.540723

In [28]:
lr.score(x_train,y_train) #training score

0.9581429684429082

In [32]:
lr.score(x_test,y_test['Salary']) #testing score

0.9407580592581604